<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends EntityRepository
{
    public function findPopular(int $count = 10)
    {
        $timeAgo = new \DateTime('now -20days');
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('h')
            ->from('AppBundle:Hashtag', 'h')
            ->leftJoin('h.news', 'n')
            ->where('n.time > :time')
            ->orderBy('n.time', 'DESC')
            ->setParameter('time', $timeAgo->format('Y-m-d'))
            ->setMaxResults($count)
            ->getQuery()
            ->getResult();

        return $result;
    }
}
