<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getAllNews($currentPage = 1)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('AppBundle:News', 'n')
            ->orderBy('n.time', 'DESC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    public function findByHashtag(string $hashtag = '')
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('AppBundle:News', 'n')
            ->leftJoin('n.hashtags', 'h')
            ->where('h.text = :hashtag')
            ->orderBy('n.time', 'DESC')
            ->setParameter('hashtag', $hashtag)
            ->setMaxResults(20)
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findByText(string $keyword = '')
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder();

        $result = $qb
            ->select('n')
            ->from('AppBundle:News', 'n')
            ->leftJoin('n.hashtags', 'h')
            ->where($qb->expr()->orX(
                $qb->expr()->like('n.text', ':keyword'),
                $qb->expr()->like('h.text', ':keyword')
            ))
            ->setParameter('keyword', '%' . $keyword . '%')
            ->orderBy('n.time', 'DESC')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function paginate($dql, $page = 1, $limit = 20)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return $paginator;
    }
}
