# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    key: '%consumer_key%'
    secret: '%consumer_secret%'
    token: '%oauth_token%'
    token_secret: '%oauth_token_secret%'

services:
    app.news_getter:
        class: AppBundle\Service\NewsGetter
        arguments: ['%key%', '%secret%', '%token%', '%token_secret%', '@service_container']